export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const RENDER_LOGIN = 'render_login'
export const LOGIN_SUCCESS = 'login_success'
export const LOGIN_FAIL = 'login_fail'
export const FB_LOGIN_SUCCESS = 'fb_login_success'
export const FB_LOGIN_FAIL = 'fb_login_fail'
export const LOADING_OFF = 'loading_off'